<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back') ?>"></a><?php TransOut('News.ArticleListForm.Title') ?></h1>
<p>
    <?php TransOut('News.ArticleListForm.Description') ?>
</p>
<?php if (!$this->hasValidLocation):?>
<p class="warning">
    <?php TransOut('News.ArticleListForm.PageContextOnly') ?>
</p>
<p>
    <a class="button-back" href="<?php HtmlOut($this->BackLink()) ?>"><?php TransOut('Core.ButtonText.Back') ?></a>
</p>
<?php else: ?>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('News.ArticleListForm.Legend') ?></legend>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('ArchiveCategory'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->articlePageSelector->Render(); ?>
            </div>
        </div>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('CssClass'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('CssID'); ?>
            </div>
        </div>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('Template'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('CacheLifetime'); ?>
            </div>
        </div>
    </fieldset>
    <?php echo $this->RenderWordingFields(); ?>
    <?php echo $this->RenderAccessElements(); ?>
    <?php echo $this->RenderSubmit(); ?>
</form>
<?php endif; ?>