<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('News.ArticleForm.Title') ?></h1>
<p>
    <?php TransOut('News.ArticleForm.Description') ?>
</p>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('News.ArticleForm.Legend') ?></legend>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('Category'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('Author'); ?>
            </div>
        </div>
        <div class="row">
            <div class="medium-12 columns">
                <?php echo $this->RenderElement('Title'); ?>
            </div>
        </div>
        <div class="row">
            <div class="medium-12 columns">
                <?php echo $this->RenderElement('Teaser'); ?>
            </div>
        </div>
        <div class="row">
            <div class="medium-12 columns">
                <?php echo $this->RenderElement('Text'); ?>
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend><?php TransOut('News.ArticleForm.Publish.Legend') ?></legend>
        <?php echo $this->RenderElement('Publish'); ?>
        <div class="row" id="PublishTimes">
            <div class="medium-6 columns">
                <div class="row">
                    <div class="medium-6 columns">
                        <?php echo $this->RenderElement('PublishFromDate'); ?>
                    </div>
                    <div class="medium-3 columns">
                        <?php echo $this->RenderElement('PublishFromHour'); ?>
                    </div>
                    <div class="medium-3 columns">
                        <?php echo $this->RenderElement('PublishFromMinute'); ?>
                    </div>
                </div>
            </div>
            <div class="medium-6 columns">
                <div class="row">
                    <div class="medium-6 columns">
                        <?php echo $this->RenderElement('PublishToDate'); ?>
                    </div>
                    <div class="medium-3 columns">
                        <?php echo $this->RenderElement('PublishToHour'); ?>
                    </div>
                    <div class="medium-3 columns">
                        <?php echo $this->RenderElement('PublishToMinute'); ?>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
    <?php echo $this->RenderSubmit(); ?>
</form>