<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('News.ArticleList.Title') ?></h1>
<p>
    <?php echo Trans('News.ArticleList.Description.Amount_{0}', $this->articlesTotal) ?>
</p>
<?php if ($this->CanCreate()): ?>
<p>
    <a href="<?php HtmlOut($this->FormUrl())?>" class="secondary button fi-plus"> <?php TransOut('News.ArticleList.New') ?></a>
</p>
<?php endif; ?>
<?php if (count($this->articles)): ?>
<div class="editable-list">
<table>
    <thead>
        <tr>
            <th><?php TransOut('News.ArticleList.ArticleTitle') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->articles as $article): ?>
        <tr>
            <td><?php HtmlOut($article->GetTitle()); ?></td>
            <td>
                <?php if ($this->CanEdit($article)): ?>
                <a class="fa fa-pencil tiny button" href="<?php HtmlOut($this->FormUrl($article)) ?>" title="<?php TransOut('News.ArticleList.Edit') ?>"></a>
                <?php endif; ?>
                <?php if ($this->CanDelete($article)): ?>
                <a href="#" class="delete-link fa fa-remove alert tiny button" data-id="<?php echo $article->GetID(); ?>" data-description="<?php TransOut('Core.ModalDelete.Description.Name_{0}', $article->GetTitle()) ?>" title="<?php TransOut('News.ArticleList.Delete') ?>"></a>
                <?php endif;  ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>
<?php endif; ?>