<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('News.CategoryForm.Title') ?></h1>
<p>
    <?php TransOut('News.CategoryForm.Title') ?>
</p>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('News.CategoryForm.Legend') ?></legend>
        
        <div class="row">
            <div class="medium-12 columns">
                <?php echo $this->RenderElement('Name'); ?>
            </div>
        </div>
    </fieldset>
    <?php echo $this->RenderSubmit(); ?>
</form>