<?php if ($this->CssID() || $this->CssClass()): ?>
<div<?php if ($this->CssClass()): ?> class="<?php HtmlOut($this->CssClass()) ?>"<?php endif; ?><?php if ($this->CssID()): ?> id="<?php HtmlOut($this->CssID()) ?>"<?php endif; ?>>
<?php endif; ?>
    <?php if (!$this->article): ?>
    <p class="article-not-available">
        <?php TransOut('News.Article.NotAvailable'); ?>
    </p>
    <?php else: ?>
    <h1 class="article-headline">
        <?php HtmlOut($this->article->GetTitle()); ?>
    </h1>
    <?php if ($this->AuthorName()): ?>
    <p class="article-author">
        <?php HtmlOut($this->AuthorName()) ?>
    </p>
    <?php endif; ?>
    <p class="article-date">
        <?php HtmlOut($this->CreateDate()) ?>
    </p>
    <p class="article-teaser">
        <?php echo $this->article->GetTeaser(); ?>
    </p>
    <p class="article-text">
        <?php echo $this->article->GetText(); ?>
    </p>
    <?php endif; ?>
<?php if ($this->CssID() || $this->CssClass()): ?>
</div>
<?php endif; ?>